version: "3.4"
services:

  init-geth:
    image: ethereum/client-go:v1.11.6
    container_name: lukso-geth-init
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init /configs/genesis.json
    logging:
      driver: "local"
      options:
        max-size: "100m"

  geth:
    image: ethereum/client-go:v1.11.6
    container_name: lukso-geth
    depends_on:
      - init-geth
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --ws
      --ws.api "eth,net"
      --ws.addr 0.0.0.0
      --ws.origins "*"
      --nat extip:$EXTERNAL_IP
      --bootnodes $GETH_BOOTSTRAP_NODE
      --networkid $GETH_NETWORK_ID
      --http
      --http.api "eth,net"
      --http.addr "0.0.0.0"
      --http.corsdomain "*"
      --http.vhosts "*"
      --verbosity $GETH_VERBOSITY
      --ipcdisable
      --port $GETH_PEER_PORT
      --http.port $GETH_HTTP_PORT
      --ethstats "${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"
      --metrics
      --metrics.addr "0.0.0.0"
      --miner.gaslimit 42000000
      --miner.gasprice 4200000000
      --authrpc.jwtsecret /configs/jwt.hex
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"

  prysm_beacon:
    image: prysmaticlabs/prysm-beacon-chain:v4.0.3
    container_name: prysm_beacon
    depends_on:
      - geth
      - eth2stats-client
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --genesis-state /configs/genesis.ssz
      --datadir /consensus_data
      --bootstrap-node $PRYSM_BOOTSTRAP_NODE
      --execution-endpoint=http://localhost:8551
      --jwt-secret=/configs/jwt.hex
      --min-sync-peers=0
      --p2p-host-ip $EXTERNAL_IP
      --chain-config-file /configs/config.yaml
      --monitoring-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --rpc-host 0.0.0.0
      --verbosity $PRYSM_VERBOSITY
      --suggested-fee-recipient $FEE_RECIPIENT
      --p2p-max-peers 250
      --subscribe-all-subnets
      --minimum-peers-per-subnet 0
      --contract-deployment-block 0
      --block-batch-limit 512
      --block-batch-limit-burst-factor 10
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"
  
  prysm_validator_import:
    image: prysmaticlabs/prysm-validator:v4.0.3
    container_name: prysm_validator_import
    volumes:
      - $KEYSTORE_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
      - $TMP_VOLUME:/tmp/secrets
    command: >
      accounts import
      --accept-terms-of-use
      --keys-dir=/tmp/secrets
      --wallet-dir=/keystore/prysm
      --wallet-password-file=/tmp/secrets/password.txt
      --account-password-file=/tmp/secrets/password.txt
    logging:
      driver: "local"
      options:
        max-size: "100m"

  prysm_validator:
    image: prysmaticlabs/prysm-validator:v4.0.3
    container_name: prysm_validator
    depends_on:
      prysm_beacon:
        condition: service_started
      prysm_validator_import:
        condition: service_completed_successfully
    volumes:
      - $KEYSTORE_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
      - $TMP_VOLUME:/tmp/secrets
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --datadir /validator_data
      --wallet-dir /keystore/prysm
      --wallet-password-file /tmp/secrets/password.txt
      --chain-config-file /configs/config.yaml
      --monitoring-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --rpc-host 0.0.0.0
      --suggested-fee-recipient $FEE_RECIPIENT
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"